appName: GeoInterpetrer
authors: Simon Tronchi, Arnaud Petit, Hicham Bouanani, Matthieu Annequin
logLevel: INFO

API:
    overpass_url: http://overpass-api.de/api/interpreter

Nearest_street:
  Binary_search:
    iter_before_increased_radius: 10
    initial_upper_bound_radius: 100
    lower_bound_radius: 0

Nearest_city:
  Binary_search:
    iter_before_increased_radius: 10
    initial_upper_bound_radius: 10000
    lower_bound_radius: 0
